Attemt to solve NumatoGpioError when response is not lowercase
clssn/numato-gpio pull request #17
Opened 2022-03-17 11:30 UTC by lwej

Hi, I have also encountered issue #14 and in my tests - this solution seems to work

I have not yet found a solution for unexpected line endings, but currently working on this..

2022-03-17 12:23 UTC, lwej commented
I am wondering if the unexpected line ending issue might be related to port range

When calling `adc_read` on 64 port module, I get the following errors:

```
Traceback (most recent call last):
  File "/..../python3.9/site-packages/numato_gpio/__init__.py", line 227, in adc_read
    try:              return int(resp[: resp.find(self._eol)])
ValueError: invalid literal for int() with base 10: ''

Traceback (most recent call last):
  File "/..../gpio.py", line 119, in <module>
    print(dev.adc_read(3))
  File "/..../python3.9/site-packages/numato_gpio/__init__.py", line 230, in adc_read
    raise NumatoGpioError(
numato_gpio.NumatoGpioError: Query ''adc read 3'' returned unexpected result '>'. Expected 10 bit decimal integer.
```

From what I can understand, this is because `adc_read` might be the only function using port directly  ?

2022-03-20 20:10 UTC, clssn requested changes
I overlooked this reading the docs. I have only 32 port devices so couldn't test a real device. Thanks for your contribution!

2022-03-20 20:10 UTC, clssn commented on src/numato_gpio/__init__.py
> +        if string.lower() != expected:
Please add a comment from which device type you expect a response in capital letters.

2022-03-21 10:52 UTC, lwej commented
> I overlooked this reading the docs. I have only 32 port devices so couldn't test a real device. Thanks for your contribution!

Thank you!

2022-03-21 21:53 UTC, clssn approved these changes

2022-03-21 21:58 UTC, merged